/**
 * API Endpoint Tests — katana-vectorbt REST API
 *
 * Tests the monitoring dashboard's REST endpoints without browser.
 * Covers /api/progress, /api/leaderboard, /api/events, and /health.
 *
 * GIVEN the Katana dashboard server is running on port 8050
 * WHEN I make GET requests to the API endpoints
 * THEN I should receive valid JSON responses with correct structure
 *
 * File location: tests/e2e/api-endpoints.spec.ts
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 *
 * Prerequisites:
 *   - Dashboard running: python -m katana.ui.monitoring_dashboard --port 8050
 *   - OR set SKIP_WEBSERVER=1 and start manually
 */

import { test, expect } from '../support/fixtures';
import { createKatanaApi } from '../support/helpers/api-helper';

test.describe('Katana REST API Endpoints', () => {

  // ─── Health Check ─────────────────────────────────────────────────────

  test.describe('GET /health', () => {
    test('returns 200 status when dashboard is running', async ({ request }) => {
      // Given: dashboard is running
      const api = createKatanaApi(request);

      // When: health check is requested
      const health = await api.checkHealth();

      // Then: service reports healthy status
      expect(health).toHaveProperty('status');
      expect(['ok', 'degraded']).toContain(health.status);
    });
  });

  // ─── Progress API ──────────────────────────────────────────────────────

  test.describe('GET /api/progress', () => {
    test('returns progress data structure when optimization is active', async ({ request }) => {
      // Given: an optimization run may be in progress
      const api = createKatanaApi(request);

      // When: progress is requested
      const progress = await api.getProgress();

      // Then: either null (no active run) or valid structure
      if (progress !== null) {
        expect(progress).toHaveProperty('status');
        expect(['RUNNING', 'COMPLETED', 'FAILED', 'PENDING']).toContain(progress.status);
        expect(progress).toHaveProperty('progress');
        expect(progress.progress).toHaveProperty('current_trial');
        expect(progress.progress).toHaveProperty('total_trials');
        expect(progress.progress).toHaveProperty('percent_complete');
        expect(progress.progress.percent_complete).toBeGreaterThanOrEqual(0);
        expect(progress.progress.percent_complete).toBeLessThanOrEqual(100);
      }
    });

    test('percent_complete is between 0 and 100', async ({ request }) => {
      const api = createKatanaApi(request);
      const progress = await api.getProgress();

      if (progress?.progress) {
        const { percent_complete, current_trial, total_trials } = progress.progress;
        expect(percent_complete).toBeGreaterThanOrEqual(0);
        expect(percent_complete).toBeLessThanOrEqual(100);
        expect(current_trial).toBeLessThanOrEqual(total_trials);
      }
    });
  });

  // ─── Leaderboard API ───────────────────────────────────────────────────

  test.describe('GET /api/leaderboard', () => {
    test('returns leaderboard with top_strategies array', async ({ request }) => {
      // Given: dashboard is running with at least some optimization history
      const api = createKatanaApi(request);

      // When: leaderboard is requested
      const leaderboard = await api.getLeaderboard();

      // Then: valid leaderboard structure is returned
      expect(leaderboard).toHaveProperty('top_strategies');
      expect(Array.isArray(leaderboard.top_strategies)).toBe(true);
    });

    test('each strategy has required trading metrics', async ({ request }) => {
      const api = createKatanaApi(request);
      const leaderboard = await api.getLeaderboard();

      for (const strategy of leaderboard.top_strategies) {
        expect(strategy).toHaveProperty('rank');
        expect(strategy).toHaveProperty('trial_id');
        expect(strategy).toHaveProperty('sharpe');
        expect(strategy).toHaveProperty('calmar');
        expect(strategy).toHaveProperty('max_dd');
        expect(strategy).toHaveProperty('params');
        // Rank should be positive integer
        expect(strategy.rank).toBeGreaterThan(0);
        // max_dd should be negative (drawdown)
        expect(strategy.max_dd).toBeLessThanOrEqual(0);
      }
    });

    test('strategies are sorted by rank ascending', async ({ request }) => {
      const api = createKatanaApi(request);
      const leaderboard = await api.getLeaderboard();

      const strategies = leaderboard.top_strategies;
      if (strategies.length > 1) {
        for (let i = 1; i < strategies.length; i++) {
          expect(strategies[i].rank).toBeGreaterThan(strategies[i - 1].rank);
        }
      }
    });
  });

  // ─── Events API ────────────────────────────────────────────────────────

  test.describe('GET /api/events', () => {
    test('returns events array', async ({ request }) => {
      // Given: dashboard is running
      const api = createKatanaApi(request);

      // When: events are requested
      const events = await api.getEvents();

      // Then: array of event objects is returned
      expect(Array.isArray(events)).toBe(true);
    });

    test('each event has required fields', async ({ request }) => {
      const api = createKatanaApi(request);
      const events = await api.getEvents();

      for (const event of events) {
        expect(event).toHaveProperty('event');
        expect(event).toHaveProperty('timestamp');
        expect(typeof event.event).toBe('string');
        expect(typeof event.timestamp).toBe('string');
        // Timestamps should be ISO 8601 format
        expect(new Date(event.timestamp).toString()).not.toBe('Invalid Date');
      }
    });
  });

  // ─── Error Handling ───────────────────────────────────────────────────

  test.describe('Error handling', () => {
    test('invalid endpoint returns 404', async ({ request }) => {
      // Given: a non-existent endpoint
      const baseUrl = process.env.DASHBOARD_URL || 'http://localhost:8050';

      // When: invalid path is requested
      const resp = await request.get(`${baseUrl}/api/nonexistent-endpoint-12345`);

      // Then: server returns 404
      expect(resp.status()).toBe(404);
    });
  });
});
