/**
 * API Helper for katana-vectorbt REST Endpoints
 *
 * Typed HTTP client covering all katana monitoring dashboard API endpoints.
 * Uses Playwright's built-in request context — no browser required.
 *
 * Endpoints tested:
 *   GET /api/progress    — Optimization run progress
 *   GET /api/leaderboard — Top strategies ranked by Sharpe
 *   GET /api/events      — Optimization event stream
 *   GET /health          — Service health check
 *
 * File location: tests/support/helpers/api-helper.ts
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 */

import type { APIRequestContext } from '@playwright/test';

// ─── Response Types ───────────────────────────────────────────────────────

export interface ProgressResponse {
  status: 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PENDING';
  progress: {
    current_trial: number;
    total_trials: number;
    percent_complete: number;
    elapsed_time_sec: number;
  };
  best_so_far: {
    trial_id: number;
    sharpe: number;
  };
}

export interface LeaderboardStrategy {
  rank: number;
  trial_id: number;
  sharpe: number;
  calmar: number;
  max_dd: number;
  params: Record<string, number>;
}

export interface LeaderboardResponse {
  top_strategies: LeaderboardStrategy[];
}

export interface EventEntry {
  event: string;
  timestamp: string;
  trial_id?: number;
  sharpe?: number;
  status?: string;
  message?: string;
}

export interface HealthResponse {
  status: 'ok' | 'degraded' | 'error';
  version?: string;
}

// ─── API Helper Class ─────────────────────────────────────────────────────

export class KatanaApiHelper {
  private readonly baseUrl: string;
  private readonly request: APIRequestContext;

  constructor(request: APIRequestContext, baseUrl?: string) {
    this.request = request;
    this.baseUrl = baseUrl
      || process.env.DASHBOARD_URL
      || process.env.BASE_URL
      || 'http://localhost:8050';
  }

  private buildUrl(path: string): string {
    return `${this.baseUrl.replace(/\/$/, '')}${path}`;
  }

  /**
   * GET /api/progress — Current optimization run progress.
   * Returns null if no run is active (404 is expected when idle).
   */
  async getProgress(): Promise<ProgressResponse | null> {
    const resp = await this.request.get(this.buildUrl('/api/progress'));
    if (resp.status() === 404) return null;
    if (!resp.ok()) {
      throw new Error(`GET /api/progress failed: HTTP ${resp.status()}`);
    }
    return resp.json() as Promise<ProgressResponse>;
  }

  /**
   * GET /api/leaderboard — Top strategies from the current or last completed run.
   */
  async getLeaderboard(): Promise<LeaderboardResponse> {
    const resp = await this.request.get(this.buildUrl('/api/leaderboard'));
    if (!resp.ok()) {
      throw new Error(`GET /api/leaderboard failed: HTTP ${resp.status()}`);
    }
    return resp.json() as Promise<LeaderboardResponse>;
  }

  /**
   * GET /api/events — Recent optimization events (SSE snapshots via polling).
   */
  async getEvents(): Promise<EventEntry[]> {
    const resp = await this.request.get(this.buildUrl('/api/events'));
    if (!resp.ok()) {
      throw new Error(`GET /api/events failed: HTTP ${resp.status()}`);
    }
    return resp.json() as Promise<EventEntry[]>;
  }

  /**
   * GET /health — Service health check. Returns false if unreachable.
   */
  async checkHealth(): Promise<HealthResponse> {
    const resp = await this.request.get(this.buildUrl('/health'));
    if (!resp.ok()) {
      throw new Error(`GET /health failed: HTTP ${resp.status()}`);
    }
    return resp.json() as Promise<HealthResponse>;
  }

  /**
   * Wait for dashboard to become available (poll /health until ready).
   * Useful in tests that start the server themselves.
   */
  async waitForReady(
    options: { timeout?: number; interval?: number } = {}
  ): Promise<void> {
    const { timeout = 30000, interval = 1000 } = options;
    const deadline = Date.now() + timeout;

    while (Date.now() < deadline) {
      try {
        await this.checkHealth();
        return; // Health check passed — server ready
      } catch {
        await new Promise((resolve) => setTimeout(resolve, interval));
      }
    }

    throw new Error(
      `Dashboard at ${this.baseUrl} did not become ready within ${timeout}ms`
    );
  }
}

/**
 * Factory function for creating KatanaApiHelper from Playwright request context.
 * Use this in fixtures to avoid constructor ceremony.
 *
 * @example
 * const api = createKatanaApi(request);
 * const progress = await api.getProgress();
 */
export function createKatanaApi(
  request: APIRequestContext,
  baseUrl?: string
): KatanaApiHelper {
  return new KatanaApiHelper(request, baseUrl);
}
