/**
 * Dashboard Page Object Model for katana-vectorbt Monitoring Dashboard
 *
 * Encapsulates all UI interactions and assertions for the Plotly Dash
 * monitoring dashboard. Uses CSS selector strategy (Dash components do not
 * support data-testid natively — Dash uses component ID attributes).
 *
 * Dashboard URL: http://localhost:8050
 * Tech stack: Plotly Dash (Python), auto-refresh every 5s
 *
 * File location: tests/support/page-objects/dashboard-page.ts
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 */

import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';

// ─── Dashboard Selectors ──────────────────────────────────────────────────

const SELECTORS = {
  // Page structure
  header: 'h1',
  subtitle: 'p',
  appContainer: '#react-entry-point',

  // Progress section (Dash component IDs)
  progressText: '#progress-text',
  progressBar: '#progress-bar',
  statusText: '#status-text',

  // Charts (Plotly)
  liveChart: '#live-chart',
  plotlyGraph: '.js-plotly-plot',
  plotlyCanvas: '.main-svg',

  // Leaderboard
  leaderboardTable: '#leaderboard-table',
  tableHeader: 'thead',
  tableBody: 'tbody',
  tableRow: 'tr',

  // Events log
  eventsLog: '#events-log',

  // Auto-refresh interval component
  intervalComponent: '#interval-component',
} as const;

// ─── Page Object ──────────────────────────────────────────────────────────

export class DashboardPage {
  readonly page: Page;

  // Header elements
  readonly header: Locator;
  readonly subtitle: Locator;

  // Progress elements
  readonly progressText: Locator;
  readonly progressBar: Locator;
  readonly statusText: Locator;

  // Chart elements
  readonly liveChart: Locator;
  readonly plotlyGraph: Locator;

  // Leaderboard elements
  readonly leaderboardTable: Locator;
  readonly tableBody: Locator;

  // Events log
  readonly eventsLog: Locator;

  constructor(page: Page) {
    this.page = page;

    this.header = page.locator(SELECTORS.header).first();
    this.subtitle = page.locator(SELECTORS.subtitle).first();

    this.progressText = page.locator(SELECTORS.progressText);
    this.progressBar = page.locator(SELECTORS.progressBar);
    this.statusText = page.locator(SELECTORS.statusText);

    this.liveChart = page.locator(SELECTORS.liveChart);
    this.plotlyGraph = page.locator(SELECTORS.plotlyGraph).first();

    this.leaderboardTable = page.locator(SELECTORS.leaderboardTable);
    this.tableBody = page.locator(SELECTORS.tableBody);

    this.eventsLog = page.locator(SELECTORS.eventsLog);
  }

  // ─── Navigation ─────────────────────────────────────────────────────────

  /**
   * Navigate to dashboard root and wait for page to load.
   * Waits for Dash React app to mount (not just network idle).
   */
  async goto(path = '/'): Promise<void> {
    await this.page.goto(path);
    await this.waitForLoad();
  }

  /**
   * Wait for the dashboard to fully load.
   * Dash apps require waiting for React hydration + initial data fetch.
   */
  async waitForLoad(): Promise<void> {
    // Wait for Dash React entry point
    await this.page.waitForSelector(SELECTORS.appContainer, { timeout: 30000 });
    // Wait for network to settle after initial Dash callback calls
    await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {
      // networkidle can time out on polling-heavy dashboards — that's OK
    });
  }

  // ─── Assertions ──────────────────────────────────────────────────────────

  /**
   * Assert dashboard is visible and header contains expected text.
   */
  async assertLoaded(expectedTitlePattern = /Katana|Optimization|Monitor/i): Promise<void> {
    await expect(this.page).toHaveTitle(expectedTitlePattern);
    await expect(this.header).toBeVisible();
  }

  /**
   * Assert Plotly chart has rendered (SVG canvas present).
   */
  async assertChartRendered(): Promise<void> {
    await expect(this.plotlyGraph).toBeVisible({ timeout: 15000 });
    const svgCanvas = this.page.locator(SELECTORS.plotlyCanvas).first();
    await expect(svgCanvas).toBeVisible({ timeout: 15000 });
  }

  /**
   * Assert the leaderboard table has at least N rows of data.
   */
  async assertLeaderboardHasRows(minRows = 1): Promise<void> {
    await expect(this.leaderboardTable).toBeVisible({ timeout: 15000 });
    const rows = this.tableBody.locator('tr');
    await expect(rows).toHaveCount(minRows, { timeout: 15000 });
  }

  /**
   * Assert the status indicator shows expected optimization status.
   */
  async assertStatus(expectedStatus: 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PENDING'): Promise<void> {
    await expect(this.statusText).toContainText(expectedStatus, { timeout: 15000 });
  }

  /**
   * Assert auto-refresh interval component is present (confirms Dash polling is active).
   */
  async assertAutoRefreshActive(): Promise<void> {
    const interval = this.page.locator(SELECTORS.intervalComponent);
    await expect(interval).toBeAttached({ timeout: 10000 });
  }

  // ─── Interactions ────────────────────────────────────────────────────────

  /**
   * Wait for auto-refresh cycle to complete (dashboard refreshes every 5s).
   * After this, the dashboard will have fetched fresh data.
   */
  async waitForAutoRefresh(refreshIntervalMs = 6000): Promise<void> {
    await this.page.waitForTimeout(refreshIntervalMs);
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  /**
   * Get the current optimization progress percentage from the UI.
   * Returns null if progress bar is not visible.
   */
  async getProgressPercent(): Promise<number | null> {
    try {
      const text = await this.progressText.textContent({ timeout: 5000 });
      const match = text?.match(/(\d+(?:\.\d+)?)\s*%/);
      return match ? parseFloat(match[1]) : null;
    } catch {
      return null;
    }
  }

  /**
   * Get all strategy rows from the leaderboard table.
   */
  async getLeaderboardRows(): Promise<string[][]> {
    await expect(this.leaderboardTable).toBeVisible({ timeout: 10000 });
    const rows = this.tableBody.locator('tr');
    const rowCount = await rows.count();

    const result: string[][] = [];
    for (let i = 0; i < rowCount; i++) {
      const cells = rows.nth(i).locator('td');
      const cellCount = await cells.count();
      const rowData: string[] = [];
      for (let j = 0; j < cellCount; j++) {
        rowData.push((await cells.nth(j).textContent()) ?? '');
      }
      result.push(rowData);
    }
    return result;
  }
}
