/**
 * Unified Test Fixtures for katana-vectorbt E2E Tests
 *
 * Pattern: mergeTests — combines custom fixtures for composable test setup.
 * All E2E tests should import { test, expect } from this file.
 *
 * File location: tests/support/fixtures/index.ts
 *
 * Architecture:
 *   Pure factory functions → Fixtures (wrapped with lifecycle) → mergeTests
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 */

import { test as base, mergeTests, expect } from '@playwright/test';
import { UserFactory } from './factories/user-factory';
import { OptimizationRunFactory } from './factories/optimization-run-factory';
import type { APIRequestContext } from '@playwright/test';

// ─── Fixture Type Definitions ─────────────────────────────────────────────

export type UserFixtures = {
  /** Factory for creating test users with realistic Faker data */
  userFactory: UserFactory;
};

export type OptimizationFixtures = {
  /** Factory for creating mock optimization run data */
  optimizationFactory: OptimizationRunFactory;
};

export type ApiFixtures = {
  /** Pre-configured API request context for katana REST endpoints */
  katanaApi: {
    getProgress: () => Promise<unknown>;
    getLeaderboard: () => Promise<unknown>;
    getEvents: () => Promise<unknown>;
    request: APIRequestContext;
  };
};

// ─── User Fixtures ────────────────────────────────────────────────────────

const userTest = base.extend<UserFixtures>({
  userFactory: async ({}, use) => {
    const factory = new UserFactory();
    await use(factory);
    await factory.cleanup();
  },
});

// ─── Optimization Data Fixtures ───────────────────────────────────────────

const optimizationTest = base.extend<OptimizationFixtures>({
  optimizationFactory: async ({}, use) => {
    const factory = new OptimizationRunFactory();
    await use(factory);
    await factory.cleanup();
  },
});

// ─── API Fixtures ─────────────────────────────────────────────────────────

const apiTest = base.extend<ApiFixtures>({
  katanaApi: async ({ request }, use) => {
    const baseUrl = process.env.DASHBOARD_URL || process.env.BASE_URL || 'http://localhost:8050';

    await use({
      request,

      async getProgress() {
        const resp = await request.get(`${baseUrl}/api/progress`);
        if (!resp.ok()) throw new Error(`Progress API failed: ${resp.status()}`);
        return resp.json();
      },

      async getLeaderboard() {
        const resp = await request.get(`${baseUrl}/api/leaderboard`);
        if (!resp.ok()) throw new Error(`Leaderboard API failed: ${resp.status()}`);
        return resp.json();
      },

      async getEvents() {
        const resp = await request.get(`${baseUrl}/api/events`);
        if (!resp.ok()) throw new Error(`Events API failed: ${resp.status()}`);
        return resp.json();
      },
    });
  },
});

// ─── Merged Export ────────────────────────────────────────────────────────

/**
 * Combined test object with all fixtures merged.
 * Import this in all E2E tests instead of @playwright/test directly.
 *
 * Available fixtures:
 * - userFactory       — UserFactory with Faker data generation
 * - optimizationFactory — OptimizationRunFactory for mock run data
 * - katanaApi         — Typed katana REST API client
 * - page              — Standard Playwright page (from base)
 * - request           — Standard Playwright request context (from base)
 */
export const test = mergeTests(userTest, optimizationTest, apiTest);
export { expect } from '@playwright/test';
