/**
 * Network Helper for katana-vectorbt E2E Tests
 *
 * Provides network interception utilities for Playwright tests targeting
 * the Plotly Dash dashboard. Enables:
 *   - Mocking Dash component callbacks (/_dash-update-component)
 *   - Intercepting REST API calls (/api/progress, /api/leaderboard, etc.)
 *   - Simulating error responses for resilience testing
 *   - Recording/replaying network calls for offline testing
 *
 * IMPORTANT: All route setup must occur BEFORE page.goto() calls.
 *
 * File location: tests/support/helpers/network-helper.ts
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 */

import type { Page, Route, Request } from '@playwright/test';

// ─── Type Definitions ─────────────────────────────────────────────────────

export interface InterceptOptions {
  /** URL pattern to intercept (glob or regex) */
  url: string | RegExp;
  /** HTTP method to match (default: any) */
  method?: string;
  /** Response to return when intercepted */
  response?: {
    status?: number;
    contentType?: string;
    body?: unknown;
    headers?: Record<string, string>;
  };
}

export interface NetworkInterception {
  /** Promise that resolves with the captured request when it fires */
  request: Promise<Request>;
  /** Remove the interception route */
  remove: () => Promise<void>;
}

// ─── Network Helper Class ─────────────────────────────────────────────────

export class DashboardNetworkHelper {
  constructor(private readonly page: Page) {}

  /**
   * Mock the /api/progress endpoint with static data.
   * Must be called BEFORE page.goto().
   *
   * @example
   * await networkHelper.mockProgressApi({ status: 'RUNNING', ... });
   * await page.goto('/');
   */
  async mockProgressApi(data: unknown, status = 200): Promise<() => Promise<void>> {
    await this.page.route('**/api/progress', (route) =>
      route.fulfill({
        status,
        contentType: 'application/json',
        body: JSON.stringify(data),
      })
    );
    return () => this.page.unroute('**/api/progress');
  }

  /**
   * Mock the /api/leaderboard endpoint with static leaderboard data.
   * Must be called BEFORE page.goto().
   */
  async mockLeaderboardApi(data: unknown, status = 200): Promise<() => Promise<void>> {
    await this.page.route('**/api/leaderboard', (route) =>
      route.fulfill({
        status,
        contentType: 'application/json',
        body: JSON.stringify(data),
      })
    );
    return () => this.page.unroute('**/api/leaderboard');
  }

  /**
   * Mock the /api/events endpoint.
   * Must be called BEFORE page.goto().
   */
  async mockEventsApi(data: unknown[], status = 200): Promise<() => Promise<void>> {
    await this.page.route('**/api/events', (route) =>
      route.fulfill({
        status,
        contentType: 'application/json',
        body: JSON.stringify(data),
      })
    );
    return () => this.page.unroute('**/api/events');
  }

  /**
   * Simulate a network error for a given URL pattern.
   * Useful for testing error handling and resilience.
   *
   * @example
   * await networkHelper.simulateNetworkError('**/api/progress');
   * await page.goto('/');
   * // Dashboard should show error state
   */
  async simulateNetworkError(urlPattern: string | RegExp): Promise<() => Promise<void>> {
    await this.page.route(urlPattern, (route) => route.abort('failed'));
    return () => this.page.unroute(urlPattern);
  }

  /**
   * Simulate a slow API response (useful for testing loading states).
   *
   * @param delayMs Delay in milliseconds before fulfilling the response
   */
  async simulateSlowApi(
    urlPattern: string | RegExp,
    data: unknown,
    delayMs = 2000
  ): Promise<() => Promise<void>> {
    await this.page.route(urlPattern, async (route) => {
      await new Promise((resolve) => setTimeout(resolve, delayMs));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(data),
      });
    });
    return () => this.page.unroute(urlPattern);
  }

  /**
   * Intercept a Dash component callback (/_dash-update-component).
   * Returns captured request data for assertions.
   *
   * @example
   * const callbackCapture = networkHelper.captureDashCallback();
   * await page.goto('/');
   * const captured = await callbackCapture;
   */
  captureDashCallback(): Promise<Request> {
    return this.page.waitForRequest('**/_dash-update-component');
  }

  /**
   * Wait for an API call to complete and capture the response.
   * Useful for asserting dashboard data loading.
   */
  waitForApiResponse(urlPattern: string | RegExp): Promise<unknown> {
    return this.page.waitForResponse(urlPattern).then((resp) => resp.json());
  }

  /**
   * Block all external network calls (only allow localhost).
   * Use in isolated tests that should not make real network requests.
   */
  async blockExternalRequests(): Promise<void> {
    await this.page.route(/^(?!https?:\/\/localhost).*/, (route: Route) => {
      route.abort('blockedbyclient');
    });
  }
}

/**
 * Factory function for creating DashboardNetworkHelper from a Playwright page.
 *
 * @example
 * const networkHelper = createNetworkHelper(page);
 * await networkHelper.mockProgressApi(mockData);
 * await page.goto('/');
 */
export function createNetworkHelper(page: Page): DashboardNetworkHelper {
  return new DashboardNetworkHelper(page);
}
