/**
 * OptimizationRunFactory — Test data factory for katana optimization runs
 *
 * Generates realistic mock data for Optuna optimization trials, leaderboard
 * entries, and strategy parameters. Tracks created entities for cleanup.
 *
 * File location: tests/support/fixtures/factories/optimization-run-factory.ts
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 */

import { faker } from '@faker-js/faker';

// ─── Type Definitions ─────────────────────────────────────────────────────

export interface StrategyParams {
  fast_ma: number;
  slow_ma: number;
  stop_loss_pct: number;
  take_profit_pct?: number;
  rsi_period?: number;
}

export interface OptimizationTrial {
  trial_id: number;
  sharpe: number;
  calmar: number;
  max_dd: number;
  params: StrategyParams;
  status: 'success' | 'failed' | 'pruned';
}

export interface OptimizationProgress {
  status: 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PENDING';
  progress: {
    current_trial: number;
    total_trials: number;
    percent_complete: number;
    elapsed_time_sec: number;
  };
  best_so_far: {
    trial_id: number;
    sharpe: number;
  };
}

export interface LeaderboardData {
  top_strategies: Array<{
    rank: number;
    trial_id: number;
    sharpe: number;
    calmar: number;
    max_dd: number;
    params: StrategyParams;
  }>;
}

// ─── Factory ──────────────────────────────────────────────────────────────

export class OptimizationRunFactory {
  private createdRunIds: number[] = [];

  /**
   * Create a single optimization trial with realistic trading metrics.
   */
  createTrial(overrides: Partial<OptimizationTrial> = {}): OptimizationTrial {
    const trial_id = faker.number.int({ min: 1, max: 999 });
    this.createdRunIds.push(trial_id);

    return {
      trial_id,
      sharpe: faker.number.float({ min: -0.5, max: 3.5, fractionDigits: 2 }),
      calmar: faker.number.float({ min: -0.2, max: 4.0, fractionDigits: 2 }),
      max_dd: faker.number.float({ min: -0.5, max: -0.05, fractionDigits: 3 }),
      params: this.createStrategyParams(),
      status: faker.helpers.arrayElement(['success', 'success', 'success', 'failed', 'pruned']),
      ...overrides,
    };
  }

  /**
   * Create strategy parameter set within valid ranges for katana strategies.
   */
  createStrategyParams(overrides: Partial<StrategyParams> = {}): StrategyParams {
    const fast_ma = faker.number.int({ min: 5, max: 30 });
    return {
      fast_ma,
      slow_ma: faker.number.int({ min: fast_ma + 5, max: 200 }),
      stop_loss_pct: faker.number.float({ min: 0.5, max: 3.0, fractionDigits: 2 }),
      take_profit_pct: faker.number.float({ min: 1.0, max: 6.0, fractionDigits: 2 }),
      rsi_period: faker.number.int({ min: 9, max: 21 }),
      ...overrides,
    };
  }

  /**
   * Create optimization progress data for a running study.
   */
  createProgress(overrides: Partial<OptimizationProgress> = {}): OptimizationProgress {
    const total_trials = faker.number.int({ min: 50, max: 500 });
    const current_trial = faker.number.int({ min: 1, max: total_trials });

    return {
      status: 'RUNNING',
      progress: {
        current_trial,
        total_trials,
        percent_complete: parseFloat(((current_trial / total_trials) * 100).toFixed(1)),
        elapsed_time_sec: faker.number.int({ min: 60, max: 7200 }),
      },
      best_so_far: {
        trial_id: faker.number.int({ min: 1, max: current_trial }),
        sharpe: faker.number.float({ min: 1.0, max: 3.5, fractionDigits: 2 }),
      },
      ...overrides,
    };
  }

  /**
   * Create a leaderboard with N top strategies (default: 10).
   */
  createLeaderboard(count = 10, overrides: Partial<LeaderboardData> = {}): LeaderboardData {
    // Generate sorted by sharpe descending
    const trials = Array.from({ length: count }, () => this.createTrial({ status: 'success' }))
      .sort((a, b) => b.sharpe - a.sharpe)
      .map((trial, idx) => ({ ...trial, rank: idx + 1 }));

    return {
      top_strategies: trials,
      ...overrides,
    };
  }

  /**
   * Create a completed optimization run with defined best strategy.
   */
  createCompletedRun(totalTrials = 100): OptimizationProgress {
    return this.createProgress({
      status: 'COMPLETED',
      progress: {
        current_trial: totalTrials,
        total_trials: totalTrials,
        percent_complete: 100.0,
        elapsed_time_sec: faker.number.int({ min: 1800, max: 14400 }),
      },
    });
  }

  async cleanup(): Promise<void> {
    // Reset tracked IDs — in a real system this would call cleanup API
    this.createdRunIds = [];
  }
}
