/**
 * Playwright Configuration for katana-vectorbt
 *
 * Project: Katana Optimization Monitoring Dashboard
 * Stack: Fullstack (Python Dash backend + Playwright TypeScript E2E)
 * Target app: Plotly Dash dashboard on port 8050
 *
 * Generated by: testarch-framework workflow (BMAD TEA v6.0.3)
 * Date: 2026-02-26
 *
 * Usage:
 *   npx playwright test                          # All tests, all browsers
 *   npx playwright test --project=chromium       # Chromium only
 *   npx playwright test tests/e2e/smoke.spec.ts  # Specific file
 *   npx playwright test --headed                 # Headed mode
 *   npx playwright test --debug                  # Debug mode
 *   npx playwright show-report                   # View HTML report
 */

import { defineConfig, devices } from '@playwright/test';

const isCI = Boolean(process.env.CI);
const baseURL = process.env.DASHBOARD_URL || process.env.BASE_URL || 'http://localhost:8050';

export default defineConfig({
  // ─── Test Directory ───────────────────────────────────────────────────────
  testDir: './tests/e2e',
  testMatch: ['**/*.spec.ts'],

  // ─── Execution ────────────────────────────────────────────────────────────
  // fullyParallel disabled: Dash dashboard is a single-process Python server.
  // Running multiple tests in parallel against the same server causes state conflicts.
  fullyParallel: false,
  workers: isCI ? 2 : 1,
  forbidOnly: isCI,
  retries: isCI ? 2 : 0,

  // ─── Timeouts ─────────────────────────────────────────────────────────────
  timeout: 60 * 1000,       // Test timeout: 60s (Dash can be slow)
  expect: {
    timeout: 15 * 1000,     // Assertion timeout: 15s
  },

  // ─── Global Settings ──────────────────────────────────────────────────────
  use: {
    baseURL,
    actionTimeout: 15 * 1000,
    navigationTimeout: 30 * 1000,

    // Artifacts: retain only on failure to keep CI storage lean
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',

    headless: true,
    ignoreHTTPSErrors: true,
    viewport: { width: 1280, height: 720 },

    // Slow-mo support for debugging (set PLAYWRIGHT_SLOW_MO=100 env var)
    launchOptions: {
      slowMo: process.env.PLAYWRIGHT_SLOW_MO
        ? Number(process.env.PLAYWRIGHT_SLOW_MO)
        : undefined,
    },
  },

  // ─── Reporters ────────────────────────────────────────────────────────────
  reporter: [
    ['html', { outputFolder: 'test-results/html', open: 'never' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
    ['line'],
    // JSON reporter for programmatic access
    ...(isCI ? [['json', { outputFile: 'test-results/results.json' }] as const] : []),
  ],

  // ─── Output Directories ───────────────────────────────────────────────────
  outputDir: 'test-results/artifacts',

  // ─── Browser Projects ─────────────────────────────────────────────────────
  projects: [
    // Primary: Chromium (fastest, used for CI smoke checks)
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    // Secondary: Firefox (cross-browser validation)
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    // Tertiary: WebKit/Safari (cross-browser validation)
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    // API-only project: No browser, for REST endpoint tests
    {
      name: 'api',
      use: {
        baseURL: process.env.API_URL || baseURL,
      },
      testMatch: ['**/api/**/*.spec.ts'],
    },
  ],

  // ─── Web Server ───────────────────────────────────────────────────────────
  // Auto-starts the Dash dashboard server for E2E tests.
  // Set SKIP_WEBSERVER=1 in .env if you start the server manually.
  webServer: process.env.SKIP_WEBSERVER
    ? undefined
    : {
        command: 'python -m katana.ui.monitoring_dashboard --port 8050',
        url: 'http://localhost:8050',
        reuseExistingServer: !isCI,
        timeout: 60 * 1000,
        stdout: 'pipe',
        stderr: 'pipe',
      },
});
