#!/usr/bin/env python3
"""
Generate Claude Skills for BMAD Workflows from CSV Registry

This script reads the workflow-manifest.csv and generates Claude skill files
(.md) for each workflow, making them available as /skill-name commands.

Usage:
    python generate-workflow-skills.py                    # Generate all workflows
    python generate-workflow-skills.py --workflow idea-to-post-pipeline  # Single workflow
    python generate-workflow-skills.py --dry-run           # Preview changes
    python generate-workflow-skills.py --update            # Update existing skills
"""

import csv
import os
import sys
from pathlib import Path
from datetime import datetime


def read_workflow_manifest(manifest_path):
    """Read workflow manifest CSV file."""
    workflows = []
    try:
        with open(manifest_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row and row.get('name'):  # Skip empty rows
                    workflows.append(row)
        return workflows
    except FileNotFoundError:
        print(f"❌ Error: Manifest file not found: {manifest_path}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error reading manifest: {e}")
        sys.exit(1)


def generate_skill_content(workflow):
    """Generate markdown content for a skill file."""
    name = workflow.get('name', '').strip('"')
    description = workflow.get('description', '').strip('"')
    module = workflow.get('module', '').strip('"')
    path = workflow.get('path', '').strip('"')

    # Create slug for command (replace hyphens with underscores for Python-like format)
    slug = name.lower().replace(' ', '-')

    # Format as YAML frontmatter + markdown
    content = f'''---
name: '{name}'
description: '{description}'
module: '{module}'
workflow_path: '{path}'
generated: {datetime.now().isoformat()}
---

# 🚀 {name.title().replace('-', ' ')}

**Module:** {module.upper()}
**Status:** Available
**Workflow:** `{name}`

## Description

{description}

## Quick Start

To use this workflow, execute:

```powershell
# Option 1: Via path
/bmad-bmb-workflow
# Select mode and enter path: {path}

# Option 2: Via config (if launcher available)
.\\run-{name}.ps1
```

## Configuration

- **Location:** `{path}`
- **Module:** {module}
- **Name:** {name}

## Related Workflows

For other workflows, check the workflow registry:
- **Registry:** `_bmad/_config/workflow-manifest.csv`
- **Commands:** `.claude/commands/`

---

**Auto-generated by:** `scripts/generate-workflow-skills.py`
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

To regenerate all skills:
```bash
python scripts/generate-workflow-skills.py
```
'''
    return content


def create_skill_file(workflow, commands_dir, dry_run=False):
    """Create or update a skill file for a workflow."""
    name = workflow.get('name', '').strip('"')

    if not name:
        return False

    skill_file = os.path.join(commands_dir, f"{name}.md")
    content = generate_skill_content(workflow)

    # Check if file exists
    file_exists = os.path.exists(skill_file)

    if dry_run:
        action = "UPDATE" if file_exists else "CREATE"
        print(f"  [{action}] {name}.md")
        return True

    try:
        # Create or overwrite the file
        with open(skill_file, 'w', encoding='utf-8') as f:
            f.write(content)

        action = "Updated" if file_exists else "Created"
        print(f"  ✅ {action}: {skill_file}")
        return True
    except Exception as e:
        print(f"  ❌ Error writing {skill_file}: {e}")
        return False


def main():
    """Main function."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Generate Claude Skills for BMAD Workflows'
    )
    parser.add_argument(
        '--workflow',
        help='Generate specific workflow (by name). Default: all workflows',
        type=str
    )
    parser.add_argument(
        '--dry-run',
        help='Preview changes without writing files',
        action='store_true'
    )
    parser.add_argument(
        '--update',
        help='Update existing skill files',
        action='store_true'
    )
    parser.add_argument(
        '--manifest',
        help='Path to workflow manifest CSV',
        default='_bmad/_config/workflow-manifest.csv',
        type=str
    )

    args = parser.parse_args()

    # Resolve paths
    project_root = Path(__file__).parent.parent
    manifest_path = project_root / args.manifest
    commands_dir = project_root / '.claude' / 'commands'

    # Ensure commands directory exists
    commands_dir.mkdir(parents=True, exist_ok=True)

    print("╔════════════════════════════════════════════════════════════╗")
    print("║      Generate Claude Skills from Workflow Manifest         ║")
    print("╚════════════════════════════════════════════════════════════╝")
    print()

    # Read manifest
    print(f"📖 Reading workflow manifest: {manifest_path}")
    workflows = read_workflow_manifest(str(manifest_path))
    print(f"✅ Found {len(workflows)} workflows")
    print()

    # Filter workflows if specified
    if args.workflow:
        workflows = [w for w in workflows if w.get('name', '').strip('"').lower() == args.workflow.lower()]
        if not workflows:
            print(f"❌ Workflow not found: {args.workflow}")
            sys.exit(1)

    # Generate skill files
    print(f"{'[DRY-RUN]' if args.dry_run else ''}Generating skill files in: {commands_dir}")
    print()

    created = 0
    updated = 0
    failed = 0

    for workflow in workflows:
        name = workflow.get('name', '').strip('"')

        if not name:
            continue

        skill_file = commands_dir / f"{name}.md"

        # Skip if exists and not update flag
        if skill_file.exists() and not args.update:
            print(f"  ⏭️  Skipped: {name}.md (use --update to override)")
            continue

        success = create_skill_file(workflow, str(commands_dir), args.dry_run)

        if success:
            if skill_file.exists():
                updated += 1
            else:
                created += 1
        else:
            failed += 1

    print()
    print("╔════════════════════════════════════════════════════════════╗")
    print(f"{'[DRY-RUN PREVIEW]' if args.dry_run else ''}Generation Summary")
    print("╚════════════════════════════════════════════════════════════╝")
    print(f"✅ Created:  {created} new skill files")
    print(f"🔄 Updated:  {updated} existing skill files")
    print(f"❌ Failed:   {failed} skill files")
    print(f"📁 Location: {commands_dir}")
    print()

    if args.dry_run:
        print("💡 Run without --dry-run to actually create files")

    if failed > 0:
        sys.exit(1)


if __name__ == '__main__':
    main()
